---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2020/10/26 11:22
---

---@class DecoratorNode : ParentNode
DecoratorNode = BaseClass(ParentNode)

---@param node TaskNode
function DecoratorNode:AddChild(node)
    if self.children == nil then
        self.children = {}
    end
    if #self.children > 0 then
        table.remove(self.children, 1)
    end
    table.insert(self.children, node)
end

function DecoratorNode:IsDecorator()
    return true
end
