---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2023/4/4 19:40
---

---@class ParentNode : TaskNode
---@field children TaskNode[]
ParentNode = BaseClass(TaskNode)

---@return TaskNode[]
function ParentNode:GetChildren()
    return self.children
end

function ParentNode:IsParent()
    return true
end

---@param child ConditionNode
function ParentNode:ReevaluateCondition(child)
    local old_state = child:GetState()
    local new_state = child:Tick()
    local is_change = old_state ~= nil and old_state ~= new_state
    --if old_state ~= new_state then
    --    self:print("状态改变", old_state, new_state)
    --end
    return is_change
end