---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/4 19:40
---

---@class ParentNode : TaskNode
---@field children TaskNode[]
ParentNode = BaseClass(TaskNode)

function ParentNode:Tick(delta_time)
	--override
end

---@return TaskNode[]
function ParentNode:GetChildren()
	return self.children
end

function ParentNode:IsParent()
	return true
end