---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2020/10/26 10:12
---

---@class logNode : ActionNode
logNode = BaseClass(ActionNode)

local _print = log
local _error = logError

function logNode:Update(delta_time)
    if self.data.is_error then
        _error(self.data.msg)
    else
        _print(self.data.msg)
    end
    return eNodeState.Success
end
