---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/26 14:08
---

SceneObjPart = {
    Main = 0,
    Weapon = 1,
    Weapon2 = 2,
    Wing = 3,
    Mount = 4,
    Tail = 5,
}

DrawPart.obj_list = {}
---@class DrawPart
DrawPart = DrawPart or BaseClass()

function DrawPart:__init()
end

function DrawPart:__delete()
end

function DrawPart.Pop()
    local draw_part = table.remove(DrawPart.obj_list)
    if not draw_part then
        draw_part = DrawPart.New()
    end
    return draw_part
end

function DrawPart.Release(draw_part)
    if #DrawPart.obj_list < 1000 then
        draw_part:Clear()
        table.insert(DrawPart.obj_list, draw_part)
    else
        draw_part:DeleteMe()
    end
end
