---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2023/4/1 17:30
---

---@class isActiveNode : ConditionNode
isActiveNode = BaseClass(ConditionNode)

function isActiveNode:Tick(delta_time)
    local gameObject = self.owner.gameObject
    if gameObject then
        if not IsNilOrEmpty(self.data.path) then
            local trans = gameObject.transform:Find(self.data.path)
            if trans and trans.gameObject then
                --self:print("Check Active")
                return trans.gameObject.activeSelf and eNodeState.success or eNodeState.failure
            end
        end
    end
    return eNodeState.failure
end