---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/26 21:18
---

require("game/mainui/MainUiData")
require("game/mainui/MainUiView")

---@class MainUiCtrl
---@field view MainUiView
MainUiCtrl = MainUiCtrl or BaseClass()

function MainUiCtrl:__init()
    if MainUiCtrl.Instance then
        print_error("[PromptCtrl] attempt to create singleton twice!")
        return
    end
    MainUiCtrl.Instance = self

    self.data = MainUiData.New()
    self.view = MainUiView.New()
end

function MainUiCtrl:__delete()
    self.gameObject = nil
    self.transform = nil
    self.panel = nil
    self.prompt = nil

    self.data:DeleteMe()
    self.data = nil

    self.view:DeleteMe()
    self.view = nil

    MainUiCtrl.Instance = nil
end

function MainUiCtrl:Open()
    --PanelMgr:CreatePanel("MainUi", BindTool.Bind(self.OnCreate, self))
    ViewManager.Instance:CreatePanel("MainUi", BindTool.Bind(self.OnCreate, self))
end

--启动事件--
function MainUiCtrl:OnCreate(obj)
    self.gameObject = obj
    self.view:AddNodeList(obj)
    self.view.node_list.btn_open_ai.button:AddClickListener(BindTool.Bind(self.OnClickOpen, self))
end

function MainUiCtrl:OnClickOpen()
    print_error(self.view.node_list.btn_open_ai.gameObject.name)
end

--单击事件--
function MainUiCtrl:OnOpenAI(go)
    AiManager.Instance:BindBT(self.gameObject, "bt1")
    AiManager.Instance:SwitchTick()
end

--关闭事件--
function MainUiCtrl:Close()
    PanelMgr:ClosePanel(CtrlNames.Message);
end