---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/23 20:52
---

---@class Vector3Pool
Vector3Pool = Vector3Pool or {}

--用于赋值给transform的无CG Vector2/Vector3
Vector3Pool._temp_vector2 = Vector2(0, 0)
Vector3Pool._temp_vector3 = Vector3(0, 0, 0)
Vector3Pool._temp_vector4 = Vector4(0, 0, 0, 0)

Vector3Pool.zero = Vector3(0, 0, 0)
Vector3Pool.one = Vector3(1, 1, 1)
Vector3Pool.rotate = Quaternion.Euler(0, 0, 0)

function Vector3Pool.GetTemp(x, y, z, w)
    if w then
        Vector3Pool._temp_vector4.x = x
        Vector3Pool._temp_vector4.y = y
        Vector3Pool._temp_vector4.z = z
        Vector3Pool._temp_vector4.w = w
        return Vector3Pool._temp_vector4
    elseif z then
        Vector3Pool._temp_vector3.x = x
        Vector3Pool._temp_vector3.y = y
        Vector3Pool._temp_vector3.z = z
        return Vector3Pool._temp_vector3
    else
        Vector3Pool._temp_vector2.x = x
        Vector3Pool._temp_vector2.y = y
        return Vector3Pool._temp_vector2
    end
end