---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2023/10/26 10:12
---

---@class parallelNode : CompositeNode
parallelNode = BaseClass(CompositeNode)

function parallelNode:Tick(delta_time)
    local state = eNodeState.Success
    if self.children then
        for _, v in ipairs(self.children) do
            local will_abort = self:GetAbortType() ~= eAbortType.None and v:IsCondition()
            if v:IsNotExecuted() or will_abort or v:IsRunning() then
                v:SetState(v:Tick(delta_time))
                if v:IsFailed() then
                    state = eNodeState.Failure
                end
            end
        end
    end
    return state
end