---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/26 14:06
---

---@class DrawObj
---@field part_list DrawPart[]
DrawObj = DrawObj or BaseClass()

function DrawObj:__init()

end