---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/26 21:18
---

require("View/MainUiPanel")
MainUiCtrl = MainUiCtrl or BaseClass()

function MainUiCtrl:__init()
    if MainUiCtrl.Instance then
        print_error("[PromptCtrl] attempt to create singleton twice!")
        return
    end
    MainUiCtrl.Instance = self
end

function MainUiCtrl:__delete()
    self.gameObject = nil
    self.transform = nil
    self.panel = nil
    self.prompt = nil

    MainUiCtrl.Instance = nil
end


function MainUiCtrl:Open()
    PanelMgr:CreatePanel("MainUi", BindTool.Bind(self.OnCreate, self))
end

--启动事件--
function MainUiCtrl:OnCreate(obj)
    self.gameObject = obj;

    self.message = self.gameObject:GetComponent('LuaBehaviour');
    self.message:AddClick(MainUiPanel.btn_open_ai, BindTool.Bind(self.OnOpenAI, self))
end

--单击事件--
function MainUiCtrl:OnOpenAI(go)
    AiManager.Instance:BindBT(self.gameObject, "bt1")
    AiManager.Instance:SwitchTick()
end

--关闭事件--
function MainUiCtrl:Close()
    PanelMgr:ClosePanel(CtrlNames.Message);
end